# Generated by Django 2.2.3 on 2019-08-06 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='inform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.Common'),
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detail',
            name='common',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Common'),
        ),
        migrations.AddField(
            model_name='comment',
            name='inform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Common'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='inform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Common'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='stamp',
            unique_together={('user', 'inform')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'inform')},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'contentId')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'inform')},
        ),
    ]
